development:
  clients:
    default:
      database: gabb
      logger: false
      hosts:
        - localhost:27017

testing:
 clients:
   default:
     uri: <%= ENV['MONGOLAB_URI'] %>
     options:
       max_retries: 30
       retry_interval: 1
       timeout: 15
       refresh_interval: 10

staging:
 clients:
   default:
     uri: <%= ENV['MONGOLAB_URI'] %>
     options:
       max_retries: 30
       retry_interval: 1
       timeout: 15
       refresh_interval: 10

production:
 clients:
   default:
     uri: <%= ENV['MONGOLAB_URI'] %>
     options:
       max_retries: 30
       retry_interval: 1
       timeout: 15
       refresh_interval: 10
